/* ===== data.js · 预设方案 + 调色板 ===== */

  const PRESETS = {
    neon:    { bg:'#8ed500', color:'#141414', borderColor:'#141414', shadowColor:'#141414',
               borderWidth:4, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
               pattern:'none', hoverInvert:true, hoverGrowShadow:false, hoverLift:false,
               hoverStraighten:false, pressShake:false, fontWeight:'900', fontFamily:'mono',
               letterSpacing:2, fontSize:16, uppercase:true },
    classic: { bg:'#ffffff', color:'#000000', borderColor:'#000000', shadowColor:'#000000',
               borderWidth:8, radius:0, rotate:-2, shadowX:14, shadowY:14, shadowBlur:0,
               pattern:'none', hoverStraighten:true, hoverGrowShadow:true, hoverLift:false,
               hoverInvert:false, pressShake:true, fontWeight:'900', fontFamily:'impact',
               letterSpacing:2, fontSize:18, uppercase:true },
    invert:  { bg:'#0a0a0a', color:'#ffffff', borderColor:'#ffffff', shadowColor:'#8ed500',
               borderWidth:3, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
               pattern:'none', hoverInvert:true, hoverGrowShadow:true, hoverLift:false,
               hoverStraighten:false, pressShake:false, fontWeight:'900', fontFamily:'mono',
               letterSpacing:3, fontSize:15, uppercase:true },
    hot:     { bg:'#ff5c39', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:5, radius:0, rotate:2, shadowX:10, shadowY:10, shadowBlur:0,
               pattern:'stripes', hoverStraighten:true, hoverGrowShadow:true, hoverLift:false,
               hoverInvert:false, pressShake:true, fontWeight:'900', fontFamily:'arialblack',
               letterSpacing:1.5, fontSize:18, uppercase:true },
    paper:   { bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:2, radius:0, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
               pattern:'grid', hoverLift:true, hoverGrowShadow:true, hoverStraighten:false,
               hoverInvert:false, pressShake:false, fontWeight:'800', fontFamily:'sans',
               letterSpacing:1, fontSize:15, uppercase:true },
    swSlab:  { bg:'#8ed500', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:5, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
               pattern:'none', swStyle:'slab', knobIcon:'bolt', motion:'step', glow:0,
               offColor:'#ffffff', fontWeight:'900', fontFamily:'mono', letterSpacing:2,
               fontSize:15, uppercase:true, hoverStraighten:false, hoverLift:false,
               hoverGrowShadow:false, hoverInvert:false, pressShake:false },
    swDouble:{ bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:6, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
               pattern:'none', swStyle:'double', knobIcon:'check', motion:'linear', glow:0,
               offColor:'#ffffff', fontWeight:'900', fontFamily:'mono', letterSpacing:2,
               fontSize:15, uppercase:true, hoverStraighten:false, hoverLift:false,
               hoverGrowShadow:false, hoverInvert:false, pressShake:false },
    swTape:  { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
               pattern:'none', swStyle:'tape', knobIcon:'cross', motion:'step', glow:6,
               offColor:'#ffffff', fontWeight:'900', fontFamily:'mono', letterSpacing:2,
               fontSize:15, uppercase:true, hoverStraighten:false, hoverLift:false,
               hoverGrowShadow:false, hoverInvert:false, pressShake:false },

    /* —— 开关 · 粗野三连 —— */
    swOffset: { bg:'#ff5c39', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:3, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', swStyle:'offset', knobIcon:'none', motion:'linear', glow:0,
                offColor:'#ffffff', fontWeight:'900', fontFamily:'mono', letterSpacing:2,
                fontSize:15, uppercase:true, hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:false, hoverInvert:false, pressShake:false },
    swStripe: { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
                pattern:'none', swStyle:'stripe', knobIcon:'cross', motion:'spring', glow:0,
                offColor:'#ffffff', fontWeight:'900', fontFamily:'mono', letterSpacing:2,
                fontSize:15, uppercase:true, hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:false, hoverInvert:false, pressShake:false },
    swSkew:   { bg:'#8ed500', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
                pattern:'none', swStyle:'skew', knobIcon:'check', motion:'bounce', glow:0,
                offColor:'#ffffff', fontWeight:'900', fontFamily:'mono', letterSpacing:2,
                fontSize:15, uppercase:true, hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:false, hoverInvert:false, pressShake:false },

    /* —— 开关 · 最新家族：网格 / 缺口 / 斜切 / 圆环 —— */
    swGrid:  { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
               pattern:'none', swStyle:'grid', knobIcon:'bolt', motion:'step', glow:0,
               offColor:'#ffffff', fontWeight:'900', fontFamily:'mono', letterSpacing:2,
               fontSize:15, uppercase:true, hoverStraighten:false, hoverLift:false,
               hoverGrowShadow:true, hoverInvert:false, pressShake:false },
    swNotch: { bg:'#ffb6e1', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:3, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
               pattern:'none', swStyle:'notch', knobIcon:'check', motion:'spring', glow:0,
               offColor:'#ffffff', fontWeight:'900', fontFamily:'mono', letterSpacing:2,
               fontSize:15, uppercase:true, hoverStraighten:false, hoverLift:false,
               hoverGrowShadow:false, hoverInvert:false, pressShake:false },
    swBevel: { bg:'#9aa0a6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:0, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
               pattern:'none', swStyle:'bevel', knobIcon:'cross', motion:'linear', glow:0,
               offColor:'#ffffff', fontWeight:'900', fontFamily:'mono', letterSpacing:2,
               fontSize:15, uppercase:true, hoverStraighten:false, hoverLift:false,
               hoverGrowShadow:true, hoverInvert:false, pressShake:false },
    swRing:  { bg:'#4d5bff', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:999, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
               pattern:'none', swStyle:'ring', knobIcon:'dot', motion:'linear', glow:0,
               offColor:'#ffffff', fontWeight:'900', fontFamily:'mono', letterSpacing:2,
               fontSize:15, uppercase:true, hoverStraighten:false, hoverLift:false,
               hoverGrowShadow:false, hoverInvert:false, pressShake:false },

    /* —— 复选框 · 粗野五连（各带不同勾选图案） —— */
    cbOffset: { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:3, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
                pattern:'none', cbStyle:'offset', cbMark:'notch',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:false, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:20, uppercase:true },
    cbInvert: { bg:'#8ed500', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', cbStyle:'invert', cbMark:'block',
                hoverStraighten:false, hoverLift:true,
                hoverGrowShadow:true, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:20, uppercase:true },
    cbHatch:  { bg:'#ff5c39', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:3, radius:0, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
                pattern:'none', cbStyle:'hatch', cbMark:'cross',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:false, hoverInvert:false, pressShake:true,
                fontWeight:'900', fontFamily:'arialblack', letterSpacing:1.5, fontSize:20, uppercase:true },
    cbBolt:   { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', cbStyle:'brutal', cbMark:'bolt',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:true, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:20, uppercase:true },
    cbBars:   { bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:2, radius:0, rotate:-2, shadowX:5, shadowY:5, shadowBlur:0,
                pattern:'grid', cbStyle:'stamp', cbMark:'bars',
                hoverStraighten:false, hoverLift:true,
                hoverGrowShadow:true, hoverInvert:false, pressShake:false,
                fontWeight:'800', fontFamily:'sans', letterSpacing:1, fontSize:20, uppercase:true },

    /* —— 复选框 · 最新家族：印章 / 网格 / 切角 / 斜切 / 四角夹框 —— */
    cbStamp: { bg:'#ffffff', color:'#d81e2c', borderColor:'#d81e2c', shadowColor:'#d81e2c',
               borderWidth:4, radius:0, rotate:-2, shadowX:0, shadowY:0, shadowBlur:0,
               pattern:'none', cbStyle:'stamp', cbMark:'notch',
               hoverStraighten:false, hoverLift:false,
               hoverGrowShadow:false, hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'impact', letterSpacing:2, fontSize:20, uppercase:true },
    cbGrid:  { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
               pattern:'none', cbStyle:'grid', cbMark:'bars',
               hoverStraighten:false, hoverLift:false,
               hoverGrowShadow:true, hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:20, uppercase:true },
    cbNotch: { bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:0, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
               pattern:'none', cbStyle:'notch', cbMark:'check',
               hoverStraighten:false, hoverLift:true,
               hoverGrowShadow:false, hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:20, uppercase:true },
    cbBevel: { bg:'#9aa0a6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:0, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
               pattern:'none', cbStyle:'bevel', cbMark:'cross',
               hoverStraighten:false, hoverLift:false,
               hoverGrowShadow:true, hoverInvert:true, pressShake:false,
               fontWeight:'900', fontFamily:'arialblack', letterSpacing:1.5, fontSize:20, uppercase:true },
    cbBracket:{ bg:'#4d5bff', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
               pattern:'none', cbStyle:'bracket', cbMark:'slash',
               hoverStraighten:false, hoverLift:false,
               hoverGrowShadow:false, hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:20, uppercase:true },

    /* —— 按钮 · 八款轮廓 —— */
    btOutline: { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
                padX:30, padY:16, pattern:'none', btnStyle:'outline',
                btnIcon:'none', btnIconPos:'right',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:true, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    btDouble:  { bg:'#ffffff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:3, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
                padX:30, padY:16, pattern:'none', btnStyle:'double',
                btnIcon:'none', btnIconPos:'right',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:true, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    btSkew:    { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:0, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
                padX:30, padY:16, pattern:'none', btnStyle:'skew',
                btnIcon:'none', btnIconPos:'right',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:false, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    btCorner:  { bg:'#ff5c39', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:0, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
                padX:30, padY:16, pattern:'none', btnStyle:'corner',
                btnIcon:'none', btnIconPos:'right',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:false, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    btRail:    { bg:'#ffffff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                padX:30, padY:16, pattern:'none', btnStyle:'rail',
                btnIcon:'none', btnIconPos:'right',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:true, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    btBracket: { bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:5, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
                padX:30, padY:16, pattern:'none', btnStyle:'bracket',
                btnIcon:'none', btnIconPos:'right',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:false, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    btPush:    { bg:'#8ed500', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
                padX:30, padY:16, pattern:'none', btnStyle:'push',
                btnIcon:'none', btnIconPos:'right',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:false, hoverInvert:false, pressShake:true,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    btArrow:   { bg:'#0a0a0a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
                padX:30, padY:16, pattern:'none', btnStyle:'solid',
                btnIcon:'arrow', btnIconPos:'right',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:true, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },

    /* —— 按钮 · 新增四款：网格纹理 / 斜贴封条 / 缺口 / 印章 —— */
    btGrid:   { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
                padX:30, padY:16, pattern:'none', btnStyle:'grid',
                btnIcon:'none', btnIconPos:'right',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:true, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    btTape:   { bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:3, radius:0, rotate:3, shadowX:6, shadowY:6, shadowBlur:0,
                padX:34, padY:16, pattern:'none', btnStyle:'tape',
                btnIcon:'none', btnIconPos:'right',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:true, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    btNotch:  { bg:'#ffb6e1', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:0, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
                padX:30, padY:16, pattern:'none', btnStyle:'notch',
                btnIcon:'none', btnIconPos:'right',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:false, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    btStamp:  { bg:'#ffffff', color:'#d81e2c', borderColor:'#d81e2c', shadowColor:'#d81e2c',
                borderWidth:4, radius:0, rotate:-2, shadowX:0, shadowY:0, shadowBlur:0,
                padX:30, padY:16, pattern:'none', btnStyle:'stamp',
                btnIcon:'none', btnIconPos:'right',
                hoverStraighten:false, hoverLift:false,
                hoverGrowShadow:false, hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'impact', letterSpacing:2.5, fontSize:16, uppercase:true },

    /* —— 输入框 · 粗野三连 —— */
    inUnder: { bg:'#ffffff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:0, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
               padX:6, padY:12, pattern:'none', inStyle:'under',
               inMark:'none', inUnit:'', inTag:'NAME', inW:320, inFocus:'press',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
               hoverInvert:false, pressShake:false,
               fontWeight:'800', fontFamily:'mono', letterSpacing:1, fontSize:17, uppercase:false },
    inTag:   { bg:'#ffffff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
               padX:18, padY:14, pattern:'none', inStyle:'label',
               inMark:'none', inUnit:'', inTag:'NAME', inW:320, inFocus:'press',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:16, uppercase:true },
    inTerm:  { bg:'#8ed500', color:'#141414', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
               padX:16, padY:14, pattern:'none', inStyle:'term',
               inMark:'prompt', inUnit:'', inTag:'NAME', inW:320, inFocus:'none',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
               hoverInvert:false, pressShake:false,
               fontWeight:'700', fontFamily:'mono', letterSpacing:1, fontSize:16, uppercase:false },
    inBracket:{ bg:'#ffffff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:5, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
               padX:20, padY:14, pattern:'none', inStyle:'bracket',
               inMark:'caret', inUnit:'', inTag:'NAME', inW:320, inFocus:'none',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
               hoverInvert:false, pressShake:false,
               fontWeight:'800', fontFamily:'mono', letterSpacing:1, fontSize:16, uppercase:false },
    inBevel: { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:0, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
               padX:20, padY:14, pattern:'none', inStyle:'bevel',
               inMark:'arrow', inUnit:'', inTag:'NAME', inW:320, inFocus:'press',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:16, uppercase:false },
    inBand:  { bg:'#8ed500', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
               padX:16, padY:12, pattern:'none', inStyle:'band',
               inMark:'hash', inUnit:'', inTag:'NAME', inW:320, inFocus:'press',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
               hoverInvert:false, pressShake:false,
               fontWeight:'800', fontFamily:'mono', letterSpacing:1, fontSize:16, uppercase:false },
    inRail:  { bg:'#ffffff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
               padX:16, padY:14, pattern:'none', inStyle:'rail',
               inMark:'dot', inUnit:'', inTag:'NAME', inW:320, inFocus:'press',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
               hoverInvert:false, pressShake:false,
               fontWeight:'800', fontFamily:'mono', letterSpacing:1, fontSize:16, uppercase:false },
    inStamp: { bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
               padX:20, padY:14, pattern:'none', inStyle:'stamp',
               inMark:'star', inUnit:'', inTag:'NAME', inW:320, inFocus:'invert',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
               hoverInvert:false, pressShake:false,
               fontWeight:'800', fontFamily:'mono', letterSpacing:1, fontSize:16, uppercase:false },
    inStripe:{ bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
               padX:16, padY:12, pattern:'none', inStyle:'stripe',
               inMark:'none', inUnit:'psi', inTag:'NAME', inW:320, inFocus:'press',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
               hoverInvert:false, pressShake:false,
               fontWeight:'800', fontFamily:'mono', letterSpacing:1, fontSize:16, uppercase:true },

    /* —— 输入框 · 最新家族：网格 / 切角 / 斜贴封条 / 内缩缺口 —— */
    inGrid:  { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
               padX:18, padY:13, pattern:'none', inStyle:'grid',
               inMark:'at', inUnit:'', inTag:'NAME', inW:340, inFocus:'press',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:16, uppercase:false },
    inNotch: { bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:0, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
               padX:18, padY:13, pattern:'none', inStyle:'notch',
               inMark:'caret', inUnit:'', inTag:'NAME', inW:340, inFocus:'press',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:16, uppercase:false },
    inCorner:{ bg:'#ff5c39', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:0, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
               padX:16, padY:13, pattern:'none', inStyle:'corner',
               inMark:'arrow', inUnit:'', inTag:'NAME', inW:340, inFocus:'none',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'arialblack', letterSpacing:1.5, fontSize:16, uppercase:false },
    inTape:  { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:-2, shadowX:0, shadowY:0, shadowBlur:0,
               padX:18, padY:13, pattern:'none', inStyle:'tape',
               inMark:'block', inUnit:'', inTag:'NAME', inW:340, inFocus:'press',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:16, uppercase:false },

    /* —— 徽章 · 形状向（徽章不共用按钮的 padX/padY，走自己的 bdPadX/bdPadY） —— */
    bdTicket: { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:0, radius:0, rotate:-3, shadowX:5, shadowY:5, shadowBlur:0,
                pattern:'none', bdStyle:'ticket', bdMark:'none', bdPadX:12, bdPadY:6,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2.5, fontSize:17, uppercase:true },
    bdBanner: { bg:'#ff3b00', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:0, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', bdStyle:'banner', bdMark:'bolt', bdPadX:16, bdPadY:7,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'arialblack', letterSpacing:2, fontSize:16, uppercase:true },
    bdZigzag: { bg:'#141414', color:'#ffe94a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:0, radius:0, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
                pattern:'none', bdStyle:'zigzag', bdMark:'star', bdPadX:14, bdPadY:8,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:3, fontSize:15, uppercase:true },
    bdStamp:  { bg:'#ffffff', color:'#d81e2c', borderColor:'#d81e2c', shadowColor:'#d81e2c',
                borderWidth:4, radius:0, rotate:-4, shadowX:0, shadowY:0, shadowBlur:0,
                pattern:'none', bdStyle:'stamp', bdMark:'none', bdPadX:16, bdPadY:8,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'impact', letterSpacing:4, fontSize:19, uppercase:true },

    /* —— 徽章 · 最新家族：折角 / 空章描边 / 侧栏 / 网格 / 切角 / 缺口 / 双线 —— */
    bdFold:   { bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:0, radius:0, rotate:-3, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', bdStyle:'fold', bdMark:'none', bdPadX:14, bdPadY:7,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    bdOutline:{ bg:'transparent', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:4, shadowY:4, shadowBlur:0,
                pattern:'none', bdStyle:'outline', bdMark:'square', bdPadX:12, bdPadY:6,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    bdSide:   { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
                pattern:'none', bdStyle:'side', bdMark:'bar', bdPadX:14, bdPadY:7,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'arialblack', letterSpacing:2, fontSize:16, uppercase:true },
    bdGrid:   { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', bdStyle:'grid', bdMark:'dot', bdPadX:13, bdPadY:7,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    bdCorner: { bg:'#ff5c39', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:0, radius:0, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
                pattern:'none', bdStyle:'corner', bdMark:'arrow', bdPadX:13, bdPadY:7,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'arialblack', letterSpacing:2, fontSize:15, uppercase:true },
    bdNotch:  { bg:'#ffb6e1', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:0, radius:0, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
                pattern:'none', bdStyle:'notch', bdMark:'star', bdPadX:14, bdPadY:8,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:3, fontSize:16, uppercase:true },
    bdDouble: { bg:'#4d5bff', color:'#ffffff', borderColor:'#ffffff', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', bdStyle:'double', bdMark:'bolt', bdPadX:14, bdPadY:7,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },

    /* —— 单选组 · 选中表态 —— */
    rdDash:   { bg:'#8ed500', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:3, radius:0, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
                pattern:'none', rdStyle:'dash', rdSize:22, rdGap:8, rdW:260,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'800', fontFamily:'mono', letterSpacing:1.5, fontSize:15, uppercase:false },
    rdInvert: { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
                pattern:'none', rdStyle:'invert', rdSize:22, rdGap:10, rdW:280,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'arialblack', letterSpacing:1, fontSize:16, uppercase:false },
    rdSkew:   { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', rdStyle:'skew', rdSize:24, rdGap:10, rdW:280,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:15, uppercase:false },
    rdStamp:  { bg:'#ffffff', color:'#d81e2c', borderColor:'#d81e2c', shadowColor:'#d81e2c',
                borderWidth:4, radius:0, rotate:-2, shadowX:0, shadowY:0, shadowBlur:0,
                pattern:'none', rdStyle:'stamp', rdSize:22, rdGap:10, rdW:260,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'impact', letterSpacing:3, fontSize:17, uppercase:false },

    /* —— 单选组 · 最新家族：切角 / 实心 / 底部粗条 / 双线外框 —— */
    rdNotch: { bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:0, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
               pattern:'none', rdStyle:'notch', rdSize:24, rdGap:9, rdW:280,
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:15, uppercase:false },
    rdBlock: { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
               pattern:'none', rdStyle:'block', rdSize:24, rdGap:10, rdW:280,
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
               hoverInvert:true, pressShake:false,
               fontWeight:'900', fontFamily:'arialblack', letterSpacing:1.5, fontSize:16, uppercase:false },
    rdBar:   { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:0, radius:0, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
               pattern:'none', rdStyle:'bar', rdSize:22, rdGap:10, rdW:280,
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:15, uppercase:false },
    rdFrame: { bg:'#ffffff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:5, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
               pattern:'none', rdStyle:'frame', rdSize:22, rdGap:9, rdW:280,
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:15, uppercase:false },

    /* —— 进度条 —— */
    pgStripe: { bg:'#ff5c39', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', pgStyle:'stripe', pgValue:68, pgW:340, pgH:30, pgShowVal:true,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:14, uppercase:true },
    pgSegment:{ bg:'#8ed500', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:4, shadowY:4, shadowBlur:0,
                pattern:'none', pgStyle:'segment', pgValue:70, pgW:340, pgH:30, pgShowVal:true,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:14, uppercase:true },
    pgNotch:  { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
                pattern:'none', pgStyle:'notch', pgValue:74, pgW:340, pgH:30, pgShowVal:false,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'impact', letterSpacing:2, fontSize:15, uppercase:true },
    pgTick:   { bg:'#141414', color:'#ffe94a', borderColor:'#ffe94a', shadowColor:'#0a0a0a',
                borderWidth:3, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
                pattern:'none', pgStyle:'tick', pgValue:58, pgW:340, pgH:32, pgShowVal:true,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2.5, fontSize:14, uppercase:true },

    /* —— 进度条 · 最新家族：双线内框 / 网格轨道 / 圆头胶囊 / 尖角推进 / 斜贴封条 —— */
    pgDouble: { bg:'#ffffff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:5, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', pgStyle:'double', pgValue:66, pgW:340, pgH:30, pgShowVal:true,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:14, uppercase:true },
    pgGrid:   { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
                pattern:'none', pgStyle:'grid', pgValue:72, pgW:340, pgH:30, pgShowVal:true,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:14, uppercase:true },
    pgPill:   { bg:'#4d5bff', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:3, radius:999, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
                pattern:'none', pgStyle:'pill', pgValue:60, pgW:340, pgH:26, pgShowVal:true,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'arialblack', letterSpacing:1, fontSize:14, uppercase:true },
    pgChevron:{ bg:'#ff5c39', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
                pattern:'none', pgStyle:'chevron', pgValue:64, pgW:340, pgH:28, pgShowVal:false,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:14, uppercase:true },
    pgTape:   { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:-2, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', pgStyle:'tape', pgValue:70, pgW:340, pgH:28, pgShowVal:true,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:14, uppercase:true },

    /* —— 滑块 —— */
    slDouble: { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', slStyle:'double', slValue:55, slW:340, slH:24, slShowVal:true,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:14, uppercase:true },
    slTick:   { bg:'#8ed500', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
                pattern:'none', slStyle:'tick', slValue:70, slW:340, slH:26, slShowVal:true,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:14, uppercase:true },
    slSkew:   { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
                pattern:'none', slStyle:'skew', slValue:62, slW:340, slH:24, slShowVal:true,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'arialblack', letterSpacing:1, fontSize:15, uppercase:true },
    slHatch:  { bg:'#ff5c39', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', slStyle:'hatch', slValue:45, slW:340, slH:26, slShowVal:true,
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:14, uppercase:true },

    /* —— 滑块 · 最新家族：网格轨道 / 大方块 / 缺口滑块 / 圆环滑块 —— */
    slGrid:{ bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
             borderWidth:4, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
             pattern:'none', slStyle:'grid', slValue:58, slW:340, slH:24, slShowVal:true,
             hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
             hoverInvert:false, pressShake:false,
             fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:14, uppercase:true },
    slBlock:{ bg:'#ffffff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
             borderWidth:5, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
             pattern:'none', slStyle:'block', slValue:62, slW:340, slH:24, slShowVal:true,
             hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
             hoverInvert:false, pressShake:false,
             fontWeight:'900', fontFamily:'arialblack', letterSpacing:1.5, fontSize:14, uppercase:true },
    slNotch:{ bg:'#ffb6e1', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
             borderWidth:3, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
             pattern:'none', slStyle:'notch', slValue:55, slW:340, slH:24, slShowVal:true,
             hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
             hoverInvert:false, pressShake:false,
             fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:14, uppercase:true },
    slRing:{ bg:'#4d5bff', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
             borderWidth:4, radius:999, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
             pattern:'none', slStyle:'ring', slValue:60, slW:340, slH:24, slShowVal:true,
             hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
             hoverInvert:false, pressShake:false,
             fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:14, uppercase:true },

    /* —— 下拉 —— */
    seDouble: { bg:'#ffffff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
                pattern:'none', seStyle:'double', seW:320, seOpts:'北京, 上海, 成都',
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'800', fontFamily:'mono', letterSpacing:1, fontSize:15, uppercase:false },
    seRail:   { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                pattern:'none', seStyle:'rail', seW:320, seOpts:'快递, 空运, 海运, 自提',
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'arialblack', letterSpacing:1, fontSize:15, uppercase:false },
    seBracket:{ bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
                pattern:'none', seStyle:'bracket', seW:320, seOpts:'标准, 加急, 特急',
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:15, uppercase:false },
    seBand:   { bg:'#141414', color:'#ffe94a', borderColor:'#8ed500', shadowColor:'#8ed500',
                borderWidth:4, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
                pattern:'none', seStyle:'band', seW:320, seOpts:'A 档, B 档, C 档',
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'impact', letterSpacing:2, fontSize:16, uppercase:true },

    /* —— 下拉 · 最新家族：印章 / 切角 / 斜切 / 网格 —— */
    seStamp: { bg:'#ffffff', color:'#d81e2c', borderColor:'#d81e2c', shadowColor:'#d81e2c',
               borderWidth:4, radius:0, rotate:-3, shadowX:0, shadowY:0, shadowBlur:0,
               pattern:'none', seStyle:'stamp', seW:320, seOpts:'原版, 复刻, 限量',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'impact', letterSpacing:2.5, fontSize:16, uppercase:true },
    seNotch: { bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:0, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
               pattern:'none', seStyle:'notch', seW:320, seOpts:'东, 西, 南, 北',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:15, uppercase:false },
    seBevel: { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:0, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
               pattern:'none', seStyle:'bevel', seW:320, seOpts:'左路, 中路, 右路',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'arialblack', letterSpacing:1.5, fontSize:15, uppercase:false },
    seGrid:  { bg:'#4d5bff', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
               borderWidth:4, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
               pattern:'none', seStyle:'grid', seW:320, seOpts:'红, 橙, 黄, 绿',
               hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
               hoverInvert:false, pressShake:false,
               fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:15, uppercase:false },

    /* —— 卡片 · 版式向 —— */
    cdBand:   { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:10, shadowY:10, shadowBlur:0,
                padX:26, padY:20, pattern:'none', cardStyle:'band', cardW:300,
                cardAlign:'left', titleRule:false, ctaStyle:'solid',
                kicker:'SPEC 04', cardTag:'A1',
                hoverStraighten:false, hoverLift:true, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:16, uppercase:true },
    cdBracket:{ bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:5, radius:0, rotate:0, shadowX:0, shadowY:0, shadowBlur:0,
                padX:28, padY:22, pattern:'grid', cardStyle:'bracket', cardW:300,
                cardAlign:'left', titleRule:true, ctaStyle:'arrow',
                kicker:'BLUEPRINT', cardTag:'',
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:false,
                hoverInvert:false, pressShake:false,
                fontWeight:'800', fontFamily:'sans', letterSpacing:1, fontSize:15, uppercase:true },
    cdBevel:  { bg:'#ff5c39', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:0, radius:0, rotate:-2, shadowX:8, shadowY:8, shadowBlur:0,
                padX:28, padY:24, pattern:'none', cardStyle:'bevel', cardW:320,
                cardAlign:'left', titleRule:true, ctaStyle:'outline',
                kicker:'CUT 45°', cardTag:'V2',
                hoverStraighten:true, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'arialblack', letterSpacing:1.5, fontSize:17, uppercase:true },
    cdNotch:  { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:0, radius:0, rotate:0, shadowX:7, shadowY:7, shadowBlur:0,
                padX:34, padY:22, pattern:'none', cardStyle:'notch', cardW:320,
                cardAlign:'left', titleRule:true, ctaStyle:'solid',
                kicker:'TICKET', cardTag:'N°7',
                hoverStraighten:false, hoverLift:true, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    cdStamp:  { bg:'#ffffff', color:'#0a0a0a', borderColor:'#d81e2c', shadowColor:'#d81e2c',
                borderWidth:5, radius:0, rotate:-2, shadowX:0, shadowY:0, shadowBlur:0,
                padX:30, padY:22, pattern:'none', cardStyle:'stamp', cardW:300,
                cardAlign:'left', titleRule:true, ctaStyle:'outline',
                kicker:'APPROVED', cardTag:'',
                hoverStraighten:false, hoverLift:true, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'impact', letterSpacing:2.5, fontSize:17, uppercase:true },
    cdRail:   { bg:'#141414', color:'#f3f3f3', borderColor:'#8ed500', shadowColor:'#8ed500',
                borderWidth:3, radius:0, rotate:0, shadowX:9, shadowY:9, shadowBlur:0,
                padX:26, padY:22, pattern:'none', cardStyle:'rail', cardW:310,
                cardAlign:'left', titleRule:true, ctaStyle:'arrow',
                kicker:'RAIL 01', cardTag:'',
                hoverStraighten:false, hoverLift:true, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:16, uppercase:true },
    cdTape:   { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:3, radius:0, rotate:1, shadowX:6, shadowY:6, shadowBlur:0,
                padX:28, padY:22, pattern:'none', cardStyle:'tape', cardW:300,
                cardAlign:'left', titleRule:true, ctaStyle:'solid',
                kicker:'TAPED', cardTag:'',
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:16, uppercase:true },

    /* —— 卡片 · 新增四款：网格纹理 / 空描边 / 切角 / 虚线硬框 —— */
    cdGrid:   { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
                padX:28, padY:22, pattern:'none', cardStyle:'grid', cardW:300,
                cardAlign:'left', titleRule:true, ctaStyle:'solid',
                kicker:'GRID A2', cardTag:'',
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:16, uppercase:true },
    cdOutline:{ bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:4, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
                padX:28, padY:22, pattern:'none', cardStyle:'outline', cardW:300,
                cardAlign:'left', titleRule:true, ctaStyle:'outline',
                kicker:'OUTLINE', cardTag:'01',
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:16, uppercase:true },
    cdCorner: { bg:'#ff5c39', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:0, radius:0, rotate:0, shadowX:9, shadowY:9, shadowBlur:0,
                padX:30, padY:24, pattern:'none', cardStyle:'corner', cardW:310,
                cardAlign:'left', titleRule:true, ctaStyle:'arrow',
                kicker:'CUT 90°', cardTag:'',
                hoverStraighten:false, hoverLift:true, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'arialblack', letterSpacing:1.5, fontSize:17, uppercase:true },
    cdDash:   { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                borderWidth:5, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
                padX:28, padY:22, pattern:'none', cardStyle:'dash', cardW:300,
                cardAlign:'left', titleRule:true, ctaStyle:'solid',
                kicker:'DASHED', cardTag:'',
                hoverStraighten:false, hoverLift:false, hoverGrowShadow:true,
                hoverInvert:false, pressShake:false,
                fontWeight:'900', fontFamily:'mono', letterSpacing:1.5, fontSize:16, uppercase:true }
  };

  const PALETTES = [
    { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a' },
    { bg:'#8ed500', color:'#141414', borderColor:'#141414', shadowColor:'#141414' },
    { bg:'#ffffff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a' },
    { bg:'#0a0a0a', color:'#8ed500', borderColor:'#8ed500', shadowColor:'#8ed500' },
    { bg:'#ff5c39', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a' },
    { bg:'#00e0ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#ff5c39' },
    { bg:'#ffb6e1', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a' },
    { bg:'#4d5bff', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#0a0a0a' },
    { bg:'#f5f0e6', color:'#0a0a0a', borderColor:'#ff5c39', shadowColor:'#0a0a0a' },
    { bg:'#141414', color:'#f3f3f3', borderColor:'#f3f3f3', shadowColor:'#8ed500' }
  ];


/* =========================================================
   新增预设配色 —— 由 build_modular.py 注入（原单文件未含）
   ========================================================= */
Object.assign(PRESETS, {
    lemon:     { bg:'#ffe94a', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                 borderWidth:6, radius:0, rotate:2, shadowX:10, shadowY:10, shadowBlur:0,
                 pattern:'none', hoverStraighten:true, hoverGrowShadow:true, hoverLift:false,
                 hoverInvert:false, pressShake:true,
                 fontWeight:'900', fontFamily:'impact', letterSpacing:1.5, fontSize:18, uppercase:true },
    cyan:      { bg:'#00e0ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#ff5c39',
                 borderWidth:4, radius:0, rotate:-2, shadowX:8, shadowY:8, shadowBlur:0,
                 pattern:'none', hoverInvert:true, hoverGrowShadow:true, hoverLift:false,
                 hoverStraighten:false, pressShake:false,
                 fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    bubble:    { bg:'#ffb6e1', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                 borderWidth:5, radius:0, rotate:-1, shadowX:6, shadowY:6, shadowBlur:0,
                 pattern:'dots', hoverLift:true, hoverGrowShadow:true, hoverStraighten:false,
                 hoverInvert:false, pressShake:false,
                 fontWeight:'900', fontFamily:'arialblack', letterSpacing:1, fontSize:16, uppercase:true },
    indigo:    { bg:'#4d5bff', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                 borderWidth:4, radius:0, rotate:0, shadowX:8, shadowY:8, shadowBlur:0,
                 pattern:'none', hoverStraighten:false, hoverGrowShadow:true, hoverLift:false,
                 hoverInvert:false, pressShake:false,
                 fontWeight:'900', fontFamily:'mono', letterSpacing:3, fontSize:15, uppercase:true },
    grape:     { bg:'#7b2cbf', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#ffe94a',
                 borderWidth:4, radius:0, rotate:-2, shadowX:8, shadowY:8, shadowBlur:0,
                 pattern:'none', hoverInvert:true, hoverGrowShadow:false, hoverLift:false,
                 hoverStraighten:false, pressShake:false,
                 fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    forest:    { bg:'#1b4332', color:'#f5f0e6', borderColor:'#f5f0e6', shadowColor:'#8ed500',
                 borderWidth:3, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                 pattern:'none', hoverStraighten:false, hoverGrowShadow:true, hoverLift:false,
                 hoverInvert:false, pressShake:false,
                 fontWeight:'800', fontFamily:'mono', letterSpacing:2, fontSize:15, uppercase:true },
    rust:      { bg:'#b7410e', color:'#fff8e7', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                 borderWidth:5, radius:0, rotate:2, shadowX:9, shadowY:9, shadowBlur:0,
                 pattern:'stripes', hoverStraighten:true, hoverGrowShadow:true, hoverLift:false,
                 hoverInvert:false, pressShake:true,
                 fontWeight:'900', fontFamily:'impact', letterSpacing:1.5, fontSize:18, uppercase:true },
    blood:     { bg:'#d90429', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                 borderWidth:5, radius:0, rotate:2, shadowX:10, shadowY:10, shadowBlur:0,
                 pattern:'none', hoverStraighten:true, hoverGrowShadow:true, hoverLift:false,
                 hoverInvert:false, pressShake:true,
                 fontWeight:'900', fontFamily:'arialblack', letterSpacing:2, fontSize:18, uppercase:true },
    mint:      { bg:'#7fffd4', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#4d5bff',
                 borderWidth:4, radius:0, rotate:-1, shadowX:7, shadowY:7, shadowBlur:0,
                 pattern:'none', hoverLift:true, hoverGrowShadow:true, hoverStraighten:false,
                 hoverInvert:false, pressShake:false,
                 fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    concrete:  { bg:'#9aa0a6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#3a3a3a',
                 borderWidth:3, radius:0, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
                 pattern:'grid', hoverStraighten:false, hoverGrowShadow:true, hoverLift:false,
                 hoverInvert:false, pressShake:false,
                 fontWeight:'800', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    blueprint: { bg:'#0b3d91', color:'#ffffff', borderColor:'#ffffff', shadowColor:'#00e0ff',
                 borderWidth:3, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                 pattern:'grid', hoverStraighten:false, hoverGrowShadow:true, hoverLift:false,
                 hoverInvert:true, pressShake:false,
                 fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:15, uppercase:true },
    coke:      { bg:'#3b2314', color:'#ffe94a', borderColor:'#ffe94a', shadowColor:'#ff5c39',
                 borderWidth:3, radius:0, rotate:0, shadowX:6, shadowY:6, shadowBlur:0,
                 pattern:'none', hoverStraighten:false, hoverGrowShadow:true, hoverLift:false,
                 hoverInvert:true, pressShake:false,
                 fontWeight:'900', fontFamily:'sans', letterSpacing:1.5, fontSize:15, uppercase:true }
});

/* ---- 新增预设配色（与上方 chip 一一对应） ---- */
Object.assign(PRESETS, {
    navy:      { bg:'#14213d', color:'#fca311', borderColor:'#fca311', shadowColor:'#fca311',
                 borderWidth:4, radius:0, rotate:-2, shadowX:8, shadowY:8, shadowBlur:0,
                 pattern:'none', hoverStraighten:true, hoverGrowShadow:true, hoverLift:false,
                 hoverInvert:false, pressShake:false,
                 fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    amber:     { bg:'#ff7a00', color:'#141414', borderColor:'#141414', shadowColor:'#141414',
                 borderWidth:5, radius:0, rotate:2, shadowX:10, shadowY:10, shadowBlur:0,
                 pattern:'stripes', hoverStraighten:true, hoverGrowShadow:true, hoverLift:false,
                 hoverInvert:false, pressShake:true,
                 fontWeight:'900', fontFamily:'impact', letterSpacing:1.5, fontSize:18, uppercase:true },
    rose:      { bg:'#ff5b8f', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a',
                 borderWidth:4, radius:0, rotate:-1, shadowX:7, shadowY:7, shadowBlur:0,
                 pattern:'dots', hoverLift:true, hoverGrowShadow:true, hoverStraighten:false,
                 hoverInvert:false, pressShake:false,
                 fontWeight:'900', fontFamily:'arialblack', letterSpacing:1.5, fontSize:16, uppercase:true },
    lavender:  { bg:'#cfa9ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#7b2cbf',
                 borderWidth:4, radius:0, rotate:1, shadowX:7, shadowY:7, shadowBlur:0,
                 pattern:'none', hoverInvert:true, hoverGrowShadow:false, hoverLift:false,
                 hoverStraighten:false, pressShake:false,
                 fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    ocean:     { bg:'#00b8d9', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#ff5c39',
                 borderWidth:4, radius:0, rotate:2, shadowX:8, shadowY:8, shadowBlur:0,
                 pattern:'none', hoverStraighten:false, hoverGrowShadow:true, hoverLift:false,
                 hoverInvert:false, pressShake:false,
                 fontWeight:'900', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true },
    silver:    { bg:'#e6e6e4', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#3a3a3a',
                 borderWidth:3, radius:0, rotate:0, shadowX:5, shadowY:5, shadowBlur:0,
                 pattern:'grid', hoverStraighten:false, hoverGrowShadow:true, hoverLift:false,
                 hoverInvert:false, pressShake:false,
                 fontWeight:'800', fontFamily:'mono', letterSpacing:2, fontSize:16, uppercase:true }
});

/* ---- 新增随机调色板（扩充「随机组合」的取色池） ---- */
PALETTES.push(
    { bg:'#7fffd4', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#4d5bff' },
    { bg:'#1b4332', color:'#f5f0e6', borderColor:'#f5f0e6', shadowColor:'#8ed500' },
    { bg:'#7b2cbf', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#ffe94a' },
    { bg:'#b7410e', color:'#fff8e7', borderColor:'#0a0a0a', shadowColor:'#0a0a0a' },
    { bg:'#d90429', color:'#ffffff', borderColor:'#0a0a0a', shadowColor:'#0a0a0a' },
    { bg:'#9aa0a6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#3a3a3a' },
    { bg:'#0b3d91', color:'#ffffff', borderColor:'#ffffff', shadowColor:'#00e0ff' },
    { bg:'#3b2314', color:'#ffe94a', borderColor:'#ffe94a', shadowColor:'#ff5c39' },
    { bg:'#ff2ea6', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#0a0a0a' },
    { bg:'#00c2ff', color:'#0a0a0a', borderColor:'#0a0a0a', shadowColor:'#ff5c39' }
);
